stages:
  - build

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

build_frontend:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week